
class Tekster {
    static String[] dukkehjem = {
    "NORA. I natt sover jeg ikke.",
    "HELMER. Men, kjære Nora -",
    "NORA (ser på sitt ur). Klokken er ennu ikke så mange. Sett deg her, Torvald; vi to har meget å tale sammen. (hun setter seg ved den ene side av bordet.)",
    "HELMER. Nora, - hva er dette her? Dette stivnede uttrykk -",
    "NORA. Sett deg ned. Det blir langt. Jeg har meget å tale med deg om.",
    "HELMER (setter seg ved bordet like overfor henne). Du engster meg, Nora. Og jeg forstår deg ikke.",
    "NORA. Nei, det er det just. Du forstår meg ikke. Og jeg har heller aldri forstått deg - før i aften. Nei, du skal ikke avbryte meg. Du skal bare høre på hva jeg sier. - Dette er et oppgjør, Torvald.",
    "HELMER. Hvorledes mener du det?",
    "NORA (efter en kort taushet). Er deg ikke én ting påfallende, således som vi sitter her?",
    "HELMER. Hva skulle det så være?",
    "NORA. Vi har nu vært gift i åtte år. Faller det deg ikke inn at det er første gang vi to, du og jeg, mann og kone, taler alvorlig sammen?",
    "HELMER. Ja, alvorlig, - hva vil det si?",
    "NORA. I åtte samfulle år, - ja lenger, - like fra vårt første bekjentskap, har vi aldri vekslet et alvorlig ord om alvorlige ting.",
    "HELMER. Skulle jeg da idelig og alltid innvie deg i bekymringer som du dog ikke kunne hjelpe meg å bære?",
    "NORA. Jeg taler ikke om bekymringer. Jeg sier vi har aldri sittet i alvor sammen for å søke å komme til bunns i noe.",
    "HELMER. Men, kjæreste Nora, ville da det ha vært for deg?",
    "NORA. Der er vi ved saken. Du har aldri forstått meg. - Der er øvet megen urett imot meg, Torvald. Først av pappa og siden av deg.",
    "HELMER. Hva! Av oss to, - av oss to der har elsket deg høyere enn alle andre mennesker?",
    "NORA (ryster på hodet). I har aldri elsket meg. I har bare syntes det var fornøyelig å være forelsket i meg.",
    "HELMER. Men Nora, hva er dette for ord?",
    "NORA. Ja, det er nu så, Torvald. Da jeg var hjemme hos pappa, så fortalte han meg alle sine meninger, og så hadde jeg de samme meninger; og hvis jeg hadde andre, så skjulte jeg det; for det ville han ikke ha likt. Han kalte meg sitt dukkebarn, og han lekte med meg som jeg lekte med mine dukker. Så kom jeg i huset til deg -",
    "HELMER. Hva er det for uttrykk du bruker om vårt ekteskap?",
    "NORA (uforstyrret). Jeg mener, så gikk jeg fra pappas hender over i dine. Du innrettet all ting efter din smak, og så fikk jeg den samme smak som du; eller jeg lot bare så; jeg vet ikke riktig -; jeg tror det var begge dele; snart det ene og snart det annet. Når jeg nu ser på det, så synes jeg jeg har levet her som et fattig menneske - bare fra hånden til munnen. Jeg har levet av å gjøre kunster for deg, Torvald. Men du ville jo ha det så. Du og pappa har gjort stor synd imot meg. I er skyld i at der ikke er blitt noe av meg.",
    "HELMER. Nora, hvor du er urimelig og utakknemlig! Har du ikke vært lykkelig her?",
    "NORA. Nei, det har jeg aldri vært. Jeg trodde det; men jeg har aldri vært det.",
    "HELMER. Ikke - ikke lykkelig!",
    "NORA. Nei; bare lystig. Og du har alltid vært så snill imot meg. Men vårt hjem har ikke vært annet enn en lekestue. Her har jeg vært din dukkehustru, liksom jeg hjemme var pappas dukkebarn. Og børnene, de har igjen vært mine dukker. Jeg syntes det var fornøyelig når du tok og lekte med meg, liksom de syntes det var fornøyelig når jeg tok og lekte med dem. Det har vært vårt ekteskap, Torvald.",
    "HELMER. Det er noe sant i hva du sier, - så overdrevent og overspent det enn er. Men herefter skal det bli annerledes. Lekens tid skal være forbi; nu kommer oppdragelsens.",
    "NORA. Hvis oppdragelse? Min eller børnenes?",
    "HELMER. Både din og børnenes, min elskede Nora.",
    "NORA. Akk, Torvald, du er ikke mann for å oppdra meg til en rett hustru for deg.",
    "HELMER. Og det sier du?",
    "NORA. Og jeg, - hvorledes er jeg forberedt til å oppdra børnene?",
    "HELMER. Nora!",
    "NORA. Sa du det ikke selv for en stund siden, - den oppgave torde du ikke betro meg.",
    "HELMER. I oppbrusningens øyeblikk! Hvor vil du akte på det?",
    "NORA. Jo; det var meget riktig sagt av deg. Jeg makter ikke den oppgave. Der er en oppgave som må løses først. Jeg må se å oppdra meg selv. Det er du ikke mann for å hjelpe meg med. Det må jeg være alene om. Og derfor reiser jeg nu fra deg.",
    "HELMER (springer opp). Hva var det du sa?",
    "NORA. Jeg må stå ganske alene hvis jeg skal få rede på meg selv og på alle ting utenfor. Derfor kan jeg ikke bli hos deg lenger.",
    "HELMER. Nora, Nora!",
    "NORA. Jeg vil gå herfra nu straks. Kristine tar nok imot meg for i natt -",
    "HELMER. Du er avsindig! Du får ikke lov! Jeg forbyr deg det!",
    "NORA. Det kan ikke nytte å forby meg noe herefter. Jeg tar med meg hva der tilhører meg selv. Av deg vil jeg ingenting ha, hverken nu eller senere.",
    "HELMER. Hvilket vanvidd er dog dette!",
    "NORA. I morgen reiser jeg hjem, - jeg mener, til mitt gamle hjemsted. Der vil det være lettest for meg å komme inn i et eller annet.",
    "HELMER. Å du forblindede, uerfarne skapning.",
    "NORA. Jeg må se å få erfaring, Torvald.",
    "HELMER. Forlate ditt hjem, din mann og dine børn! Og du tenker ikke på hva folk vil si.",
    "NORA. Det kan jeg ikke ta noe hensyn til. Jeg vet bare det blir nødvendig for meg.",
    "HELMER. Å, det er opprørende. Således kan du svikte dine helligste plikter.",
    "NORA. Hva regner du da for mine helligste plikter?",
    "HELMER. Og det skal jeg behøve å si deg! Er det ikke pliktene imot din mann og dine børn?",
    "NORA. Jeg har andre likså hellige plikter.",
    "HELMER. Det har du ikke. Hvilke plikter skulle det være.",
    "NORA. Pliktene imot meg selv.",
    "HELMER. Du er først og fremst hustru og mor.",
    "NORA. Det tror jeg ikke lenger på. Jeg tror at jeg er først og fremst et menneske, jeg, likså vel som du, - eller iallfall at jeg skal forsøke på å bli det. Jeg vet nok at de fleste gir deg rett, Torvald, at det står noe slikt i bøkene. Men jeg kan ikke lenger la meg nøye med hva de fleste sier, og hva der står i bøkene. Jeg må selv tenke over de ting og se å få rede på dem.",
    "HELMER. Du skulle ikke ha rede på din stilling i ditt eget hjem? Har du ikke i sånne spørsmål en usvikelig veileder? Har du ikke religionen?",
    "NORA. Akk, Torvald, jeg vet jo slett ikke riktig hva religionen er.",
    "HELMER. Hva er det du sier!",
    "NORA. Jeg vet jo ikke annet enn hva presten Hansen sa da jeg gikk til konfirmasjonen. Han fortale at religionen var det og det. Når jeg kommer bort fra alt dette her og blir ensom, så vil jeg undersøke den sak også. Jeg vil se om det var riktig hva presten Hansen sa, eller iallfall om det er riktig for meg.",
    "HELMER. Å, slikt er dog uhørt av en så ung kvinne! Men kan ikke religionen rettlede deg, så la meg dog ryste opp i din samvittighet. For moralsk følelse har du dog? Eller, svar meg, - har du kanskje ingen?",
    "NORA. Ja, Torvald, det er ikke godt å svare på det. Jeg vet det jo slett ikke. Jeg er ganske i villrede med de ting. Jeg vet bare at jeg har en ganske annen mening om slikt noe enn du. Jeg hører også nu at lovene er annerledes enn jeg tenkte; men at de love skulle være riktige, det kan jeg umulig få i mitt hode. En kvinne skal altså ikke ha rett til å skåne sin gamle døende far, eller til å redde sin manns liv! Slikt tror jeg ikke på.",
    "HELMER. Du taler som et barn. Du forstår ikke det samfunn du lever i.",
    "NORA. Nei, det gjør jeg ikke. Men nu vil jeg sette meg inn i det. Jeg må se å komme efter hvem der har rett, samfunnet eller jeg.",
    "HELMER. Du er syk, Nora; du har feber; jeg tror nesten du er fra sans og samling.",
    "NORA. Jeg har aldri følt meg så klar og sikker som i natt.",
    "HELMER. Og klar og sikker forlater du din mann og dine børn?",
    "NORA. Ja; det gjør jeg.",
    "HELMER. Så er kun én forklaring mulig.",
    "NORA. Hvilken?",
    "HELMER. Du elsker meg ikke mer.",
    "NORA. Nei, det er just tingen.",
    "HELMER. Nora! - Og det sier du!",
    "NORA. Å, det gjør meg så ondt, Torvald; for du har alltid vært så snill imot meg. Men jeg kan ikke gjøre ved det. Jeg elsker deg ikke mer.",
    "HELMER (med tilkjempet fatning). Er dette også en klar og sikker overbevisning?",
    "NORA. Ja, fullkommen klar og sikker. Det er derfor jeg ikke vil være her lenger.",
    "HELMER. Og vil du også kunne gjøre meg rede for hvorved jeg har forspilt din kjærlighet?",
    "NORA. Ja, det kan jeg godt. Det var i aften da det vidunderlige ikke kom; for da så jeg at du ikke var den mann jeg hadde tenkt meg.",
    "HELMER. Forklar deg nøyere; jeg begriper deg ikke.",
    "NORA. Jeg har ventet så tålmodig nu i åtte år; for Herregud, jeg innså jo nok at det vidunderlige kommer ikke sånn til hverdags. Så brøt dette knusende inn over meg; og da var jeg så usvikelig viss på: nu kommer det vidunderlige. Da Krogstads brev lå der ute, - aldri falt det meg med en tanke inn at du kunne ville bøye deg under dette menneskes vilkår. Jeg var så usvikelig viss på at du ville si til ham: gjør saken bekjent for hele verden. Og når det var skjedd -",
    "HELMER. Ja hva så? Når jeg hadde prisgitt min egen hustru til skam og skjensel -!",
    "NORA. Når det var skjedd, da tenkte jeg så usvikelig sikkert at du ville tre frem og ta alt på deg og si: jeg er den skyldige.",
    "HELMER. Nora -!",
    "NORA. Du mener at jeg aldri ville tatt imot et slikt offer av deg? Nei, det forstår seg. Men hva ville mine forsikringer gjelde like overfor dine? - Det var det vidunderlige som jeg gikk og håpet på i redsel. Og for å hindre det, var det at jeg ville ende mitt liv.",
    "HELMER. Jeg skulle gladelig arbeide netter og dage for deg, Nora, - bære sorg og savn for din skyld. Men der er ingen som ofrer sin ære for den man elsker.",
    "NORA. Det har hundre tusen kvinner gjort.",
    "HELMER. Å, du både tenker og du taler som et uforstandig barn.",
    "NORA. La gå. Men du hverken tenker eller taler som den mann jeg skal kunne slutte meg til. Da din forskrekkelse var over, - ikke for hva der truet meg, men for hva du selv var utsatt for, og da hele faren var forbi, - da var det for deg som om slett ingen ting var skjedd. Jeg var akkurat som før din lille sanglerke, din dukke, som du herefter skulle bære dobbelt varlig på hendene, siden den var så skjør og skrøpelig. (reiser seg.) Torvald, - i den stund gikk det opp for meg at jeg i åtte år hadde levet her sammen med en fremmed mann, og at jeg hadde fått tre børn -. Å jeg tåler ikke å tenke på det! Jeg kunne rive meg selv i stumper og stykker.",
    "HELMER (tungt). Jeg ser det; jeg ser det. Der er visselig kommet en avgrunn imellem oss. - Å, men, Nora, skulle den ikke kunne utfylles?",
    "NORA. Således som jeg nu er, er jeg ingen hustru for deg.",
    "HELMER. Jeg har kraft til å bli en annen.",
    "NORA. Måskje, - hvis dukken tas fra deg.",
    "HELMER. Å skilles - skilles fra deg! Nei, nei, Nora, jeg kan ikke fatte den tanke.",
    "NORA (går inn til høyre). Dess vissere må det skje. (hun kommer tilbake med sitt yttertøy og en liten vadsekk, som hun setter på stolen ved bordet.)",
    "HELMER. Nora, Nora, ikke nu! Vent til i morgen.",
    "NORA (tar kåpen på). Jeg kan ikke bli liggende natten over i en fremmed manns værelser.",
    "HELMER. Men kan vi da ikke bo her som bror og søster -?",
    "NORA (binder hatten fast). Du vet meget godt det ville ikke vare lenge -. (slår sjalet om seg.) Farvel, Torvald. Jeg vil ikke se de små. Jeg vet de er i bedre hender enn mine. Således som jeg nu er, kan jeg ingen ting være for dem.",
    "HELMER. Men en gang, Nora, - en gang -?",
    "NORA. Hvor kan jeg vite det? Jeg vet jo slett ikke hva der blir ut av meg.",
    "HELMER. Men du er min hustru, både som du er, og som du blir.",
    "NORA. Hør, Torvald; - når en hustru forlater sin manns hus, således som jeg nu gjør, så har jeg hørt at han efter loven er løst fra alle forpliktelser imot henne. Jeg løser deg iallfall fra enhver forpliktelse. Du skal ikke føle deg bundet ved noe, like så litt som jeg vil være det. Der må være full frihet på begge sider. Se her har du din ring tilbake. Gi meg min.",
    "HELMER. Også dette?",
    "NORA. Dette også.",
    "HELMER. Her er den.",
    "NORA. Så. Ja, nu er det altså forbi. Her legger jeg nøklene. Om alle saker i huset vet pikene beskjed - bedre enn jeg. I morgen, når jeg er reist, kommer Kristine her hen for å pakke sammen de ting som er min eiendom hjemmefra. Det vil jeg ha sendt efter meg.",
    "HELMER. Forbi; forbi! Nora, vil du aldri mer tenke på meg?",
    "NORA. Jeg kommer visst ofte til å tenke på deg og på børnene og på huset her.",
    "HELMER. Må jeg skrive deg til, Nora?",
    "NORA. Nei, - aldri. Det får du ikke lov til.",
    "HELMER. Å, men sende deg må jeg dog -",
    "NORA. Intet; intet.",
    "HELMER. - hjelpe deg hvis du skulle behøve det.",
    "NORA. Nei, sier jeg. Jeg mottar ingen ting av fremmede.",
    "HELMER. Nora, - kan jeg aldri bli mer enn en fremmed for deg?",
    "NORA. (tar sin vadsekk). Akk, Torvald, da måtte det vidunderligste skje. -",
    "HELMER. Nevn meg dette vidunderligste!",
    "NORA. Da måtte både du og jeg forvandle oss således at -. Å, Torvald, jeg tror ikke lenger på noe vidunderlig.",
    "HELMER. Men jeg vil tro på det. Nevn det! Forvandle oss således at -?",
    "NORA. At samliv mellom oss to kunne bli et ekteskap. Farvel.",
    "(hun går ut gjennem forstuen.)",
    "HELMER. (synker ned på en stol ved døren og slår hendene for ansiktet). Nora! Nora! (ser seg om og reiser seg.) Tomt. Hun er her ikke mer. (et håp skyter opp i ham.) Det vidunderligste -?!"
    };

    static String[] grunnloven = {
    "Kongeriket Norges Grunnlov gitt i riksforsamlingen på Eidsvoll den 17. mai 1814, slik den lyder etter senere endringer, senest grunnlovsvedtak av 13. mai 2014.",
    "A. Om statsformen",
    "§1 Kongeriket Norge er et fritt, selvstendig, udelelig og uavhendelig rike. Dets regjeringsform er innskrenket og arvelig monarkisk.",
    "§2 Verdigrunnlaget forblir vår kristne og humanistiske arv. Denne Grunnlov skal sikre demokratiet, rettsstaten og menneskerettighetene.",
    "B. Om den utøvende makt, kongen og den kongelige familie og om religionen",
    "§3 Den utøvende makt er hos kongen eller hos dronningen, hvis hun har ervervet kronen etter bestemmelsene i § 6, § 7 eller § 48 i denne Grunnlov. Når den utøvende makt således er hos dronningen, har hun alle de rettigheter og plikter som ifølge denne Grunnlov og landets lover innehas av kongen.",
    "§4 Kongen skal alltid bekjenne seg til den evangelisk-lutherske religion.",
    "§5 Kongens person er hellig; han kan ikke lastes eller anklages. Ansvarligheten påligger hans råd.",
    "§6 Arvefølgen er lineal, således at bare i lovlig ekteskap født barn av konge eller dronning eller av en som selv er arveberettiget, kan arve, og at den nærmere linje går foran den fjernere og den eldre i linjen foran den yngre. Blant arveberettigede regnes også den ufødte, som straks inntar sitt tilbørlige sted i arvelinjen når han eller hun fødes til verden. Dog tilkommer arverett ikke noen som ikke er født i rett nedstigende linje fra den sist regjerende konge eller dronning eller fra dennes bror eller søster, eller selv er dennes bror eller søster. Når en til Norges krone arveberettiget prins eller prinsesse fødes, skal hans eller hennes navn og fødselstid tilkjennegis førstholdende storting og antegnes i dets protokoll. For dem som er født tidligere enn året 1971, gjelder dog denne Grunnlovs § 6 således som den ble vedtatt den 18. november 1905. For dem som er født tidligere enn året 1990, gjelder likevel at mann går foran kvinne.",
    "§7 Er ingen arveberettiget prins eller prinsesse til,kan kongen foreslå sin etterfølger for Stortinget, som har rett til å bestemme valget hvis kongens forslag ikke bifalles.",
    "§8 Kongens myndighetsalder fastsettes ved lov. Så snart kongen har oppnådd den lovbestemte alder, erklærer han seg offentlig å være myndig.",
    "§9 Så snart kongen, som myndig, tiltrer regjeringen, avlegger han følgende ed for Stortinget: «Jeg lover og sverger å ville regjere kongeriket Norge i overensstemmelse med dets konstitusjon og lover, så sant hjelpe meg Gud den allmektige og allvitende!» Er intet storting på den tid samlet, nedlegges eden skriftlig i statsrådet og gjentas høytidelig av kongen på første storting."
    };

    static String[] ojd = {
    "Ole-Johan Dahl (October 12, 1931 / June 29, 2002) was a Norwegian computer scientist and is considered to be the father of Simula and object-oriented programming, together with Kristen Nygaard.",
    "Dahl is a member of the small group of scientists who will be regarded as founders of their own field of science. His field was informatics and he won the two most prestigious international prizes specific to that field: The ACM A.M. Turing Award (considered to be the \"Nobel Prize of Computing\"), in 2001 and the IEEE John von Neumann Medal. He was made Commander of The Order of Saint Olav by the King of Norway in 2000, and received a number of other signs of recognition.",
    "With Kristen Nygaard, he produced the initial ideas for object-oriented (OO) programming in the 1960s at the Norwegian Computing Center (NR - Norsk Regnesentral) as part of the Simula I (1961-1965) and Simula 67 (1965-1968) simulation programming languages",
    "Dahl and Nygaard were the first to develop the concepts of class, subclass (allowing information hiding), inheritance, dynamic object creation, etc., all important aspects of the OO paradigm. Their work has led to a fundamental change in how software systems are designed and programmed, resulting in reusable, reliable, scalable applications that have streamlined the process of writing software code and facilitated software programming. Current object-oriented programming languages include C++ and Java, both widely used in programming a wide range of applications from large-scale distributed systems to small, personal applications, including personal computers, home entertainment devices, and stand-alone arcade applications.",
    "Dahl became a full professor in 1968 at the University of Oslo, creating the discipline of computer science here. He was the first professor of informatics, responsible for establishing research and education programs in this rapidly expanding field. Here he worked on Hierarchical Program Structures, probably his most influential publication, which appeared co-authored with C.A.R. Hoare in the influential book Structured Programming of 1972 by Dahl, Dijkstra and Hoare, perhaps the best-known academic book concerning software in the 1970s.",
    "In his University career, Dahl focused on the use of formal methods, to rigorously reason about programs. Unlike many theoretical computer scientists at the time, his work had a solid motivation in practical applicability and implementation experience. With Owe, who became his closest collaborator, he investigated languages, specification, verification and related tool development, in the long term ABEL project, and in the development of formal methods for object-orientation. His research is today represented and continued by the PMA research group."
    };

    static String[][] tekster = {ojd, dukkehjem, grunnloven};
    static int ANTALL_TEKSTER = tekster.length;
}
